/**
 * Seed data configuration for the Tembea Africa database.
 * This file defines all static seed data and makes it easy to add more.
 * To add new seed data:
 * 1. Add it to the appropriate collection below
 * 2. It will automatically be included when seeding
 */

import * as bcrypt from 'bcryptjs'

export interface SeedConfig {
  clearCollections: boolean  // Clear existing data before seeding
  collections: {
    [key: string]: any[]
  }
}

export async function generateSeedData(): Promise<SeedConfig> {
  const hashedPassword = await bcrypt.hash('Hamp9map....#', 12)

  // ─── USERS ─────────────────────────────────────────────────────────────────
  const users = [
    {
      _id: 'admin-user-id',
      firstName: 'Admin',
      lastName: 'Tembea',
      email: 'tembeaafricake@gmail.com',
      password: hashedPassword,
      role: 'admin',
      isVerified: true,
      createdAt: new Date(),
    },
    {
      _id: 'guide-joseph-id',
      firstName: 'Joseph',
      lastName: 'Kamau',
      email: 'joseph@tembeaafrica.com',
      password: hashedPassword,
      role: 'guide',
      isVerified: true,
      createdAt: new Date(),
    },
    {
      _id: 'guide-amina-id',
      firstName: 'Amina',
      lastName: 'Mohamed',
      email: 'amina@tembeaafrica.com',
      password: hashedPassword,
      role: 'guide',
      isVerified: true,
      createdAt: new Date(),
    },
    {
      _id: 'tourist-john-id',
      firstName: 'John',
      lastName: 'Traveller',
      email: 'john@example.com',
      password: hashedPassword,
      role: 'tourist',
      isVerified: true,
      createdAt: new Date(),
    },
    {
      _id: 'tourist-sarah-id',
      firstName: 'Sarah',
      lastName: 'Williams',
      email: 'sarah@example.com',
      password: hashedPassword,
      role: 'tourist',
      isVerified: true,
      nationality: 'United Kingdom',
      createdAt: new Date(),
    },
    {
      _id: 'operator-mara-id',
      firstName: 'Mara',
      lastName: 'Safaris',
      email: 'operator@marasafaris.com',
      password: hashedPassword,
      role: 'operator',
      isVerified: true,
      createdAt: new Date(),
    },
  ]

  // ─── DESTINATIONS ──────────────────────────────────────────────────────────
  const destinations = [
    {
      _id: 'destination-mara-id',
      name: 'Maasai Mara',
      slug: 'maasai-mara',
      country: 'kenya',
      county: 'Narok',
      description: 'Home to the Great Wildebeest Migration and Africa\'s finest Big Five wildlife viewing.',
      heroImage: 'https://images.unsplash.com/photo-1547970810-dc1eac37d174?w=1200',
      images: ['https://images.unsplash.com/photo-1547970810-dc1eac37d174?w=800'],
      coordinates: { lat: -1.5001, lng: 35.1399 },
      rating: 4.9,
      reviewCount: 1240,
      tourCount: 86,
      hotelCount: 45,
      tags: ['Wildlife', 'Safari', 'Migration', 'Big Five'],
      bestTimeToVisit: 'July–October',
      featured: true,
      status: 'active',
      travelTips: 'Book sunrise game drives for best predator sightings.',
      visaInfo: 'Kenya eVisa available online at $51.',
      createdAt: new Date(),
    },
    {
      _id: 'destination-zanzibar-id',
      name: 'Zanzibar',
      slug: 'zanzibar',
      country: 'tanzania',
      description: 'Pristine white sandy beaches, turquoise Indian Ocean waters, and rich Swahili cultural heritage.',
      heroImage: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200',
      images: ['https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800'],
      coordinates: { lat: -6.1659, lng: 39.2026 },
      rating: 4.8,
      reviewCount: 890,
      tourCount: 54,
      hotelCount: 120,
      tags: ['Beach', 'Culture', 'Diving', 'Spice'],
      bestTimeToVisit: 'June–October',
      featured: true,
      status: 'active',
      createdAt: new Date(),
    },
    {
      _id: 'destination-kilimanjaro-id',
      name: 'Kilimanjaro',
      slug: 'kilimanjaro',
      country: 'tanzania',
      description: 'Africa\'s highest peak at 5,895m. The ultimate trekking challenge attracting climbers from across the globe.',
      heroImage: 'https://images.unsplash.com/photo-1621414050345-53db43f7e7ab?w=1200',
      images: ['https://images.unsplash.com/photo-1621414050345-53db43f7e7ab?w=800'],
      coordinates: { lat: -3.0674, lng: 37.3556 },
      rating: 4.9,
      reviewCount: 620,
      tourCount: 32,
      hotelCount: 28,
      tags: ['Trekking', 'Adventure', 'Mountain', 'Summit'],
      bestTimeToVisit: 'January–March, June–October',
      featured: true,
      status: 'active',
      createdAt: new Date(),
    },
    {
      _id: 'destination-serengeti-id',
      name: 'Serengeti',
      slug: 'serengeti',
      country: 'tanzania',
      description: 'Endless golden plains hosting the world\'s greatest wildlife spectacle — year-round Big Five and the Great Migration.',
      heroImage: 'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=1200',
      images: ['https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=800'],
      coordinates: { lat: -2.3333, lng: 34.8333 },
      rating: 5.0,
      reviewCount: 1100,
      tourCount: 98,
      hotelCount: 62,
      tags: ['Wildlife', 'Safari', 'Photography', 'Migration'],
      bestTimeToVisit: 'June–September',
      featured: true,
      status: 'active',
      createdAt: new Date(),
    },
    {
      _id: 'destination-mombasa-id',
      name: 'Mombasa',
      slug: 'mombasa',
      country: 'kenya',
      description: 'Kenya\'s vibrant coastal city blending Old Town Swahili heritage with beautiful Indian Ocean beaches.',
      heroImage: 'https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=1200',
      images: ['https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=800'],
      coordinates: { lat: -4.0435, lng: 39.6682 },
      rating: 4.7,
      reviewCount: 980,
      tourCount: 71,
      hotelCount: 134,
      tags: ['Beach', 'History', 'Culture', 'City'],
      bestTimeToVisit: 'October–April',
      featured: true,
      status: 'active',
      createdAt: new Date(),
    },
    {
      _id: 'destination-diani-id',
      name: 'Diani Beach',
      slug: 'diani-beach',
      country: 'kenya',
      description: 'Kenya\'s most celebrated beach — 17km of powder-white sand, coral reefs, and world-class resorts.',
      heroImage: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1200',
      images: ['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800'],
      coordinates: { lat: -4.2947, lng: 39.5748 },
      rating: 4.8,
      reviewCount: 560,
      tourCount: 38,
      hotelCount: 67,
      tags: ['Beach', 'Snorkeling', 'Relaxation', 'Diving'],
      bestTimeToVisit: 'December–April',
      featured: true,
      status: 'active',
      createdAt: new Date(),
    },
  ]

  // ─── TOURS ─────────────────────────────────────────────────────────────────
  const tours = [
    {
      title: '5-Day Maasai Mara Safari — Big Five Guaranteed',
      slug: 'maasai-mara-big-five-5day',
      description: 'Immerse yourself in the heart of the Maasai Mara on this 5-day safari. Witness lions, leopards, elephants, buffalos, and rhinos up close.',
      destination: 'destination-mara-id',
      operator: 'operator-mara-id',
      category: 'safari',
      images: ['https://images.unsplash.com/photo-1547970810-dc1eac37d174?w=800'],
      price: 480,
      currency: 'USD',
      duration: '5 days',
      groupSize: 8,
      rating: 4.9,
      reviewCount: 312,
      featured: true,
      instantBooking: true,
      status: 'active',
      includes: ['4WD safari vehicle', 'Professional guide', 'Park fees', 'Accommodation', 'All meals', 'Airport pickup'],
      excludes: ['International flights', 'Travel insurance', 'Tips', 'Personal items'],
      tags: ['Safari', 'Big Five', 'Luxury', 'Kenya'],
      totalBookings: 156,
      isDeleted: false,
      createdAt: new Date(),
    },
    {
      title: 'Zanzibar Island Dhow Cruise & Spice Tour',
      slug: 'zanzibar-dhow-cruise-spice',
      description: 'Sail on a traditional wooden dhow along Zanzibar\'s turquoise coast, then explore fragrant spice plantations.',
      destination: 'destination-zanzibar-id',
      operator: 'operator-mara-id',
      category: 'beach',
      images: ['https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800'],
      price: 75,
      currency: 'USD',
      duration: '1 day',
      groupSize: 12,
      rating: 4.8,
      reviewCount: 197,
      featured: true,
      instantBooking: true,
      status: 'active',
      includes: ['Dhow boat', 'Snorkeling equipment', 'Lunch on boat', 'Spice farm entry', 'Guide'],
      excludes: ['Hotel pickup', 'Alcoholic drinks'],
      tags: ['Beach', 'Dhow', 'Spices', 'Snorkeling'],
      totalBookings: 89,
      isDeleted: false,
      createdAt: new Date(),
    },
    {
      title: 'Kilimanjaro Summit Trek — 7 Days Machame Route',
      slug: 'kilimanjaro-machame-7day',
      description: 'Conquer Africa\'s highest peak via the scenic Machame "Whiskey" route with our KWS-certified mountain guides.',
      destination: 'destination-kilimanjaro-id',
      operator: 'operator-mara-id',
      category: 'mountain',
      images: ['https://images.unsplash.com/photo-1621414050345-53db43f7e7ab?w=800'],
      price: 1850,
      currency: 'USD',
      duration: '7 days',
      groupSize: 6,
      rating: 4.9,
      reviewCount: 88,
      featured: true,
      instantBooking: false,
      status: 'active',
      includes: ['KWS-certified guide', 'Porters', 'All meals on mountain', 'Camping equipment', 'Park fees', 'Transfers'],
      excludes: ['International flights', 'Sleeping bag', 'Tips', 'Travel insurance'],
      tags: ['Trekking', 'Summit', 'Adventure', 'Mountain'],
      totalBookings: 42,
      isDeleted: false,
      createdAt: new Date(),
    },
    {
      title: 'Maasai Mara Balloon Safari at Sunrise',
      slug: 'mara-balloon',
      description: 'Float above the Mara at dawn with champagne breakfast. Witness wildlife migrations from a birds-eye view.',
      destination: 'destination-mara-id',
      operator: 'operator-mara-id',
      category: 'adventure',
      images: ['https://images.unsplash.com/photo-1547970810-dc1eac37d174?w=800'],
      price: 320,
      currency: 'USD',
      duration: '4 hours',
      groupSize: 8,
      rating: 5.0,
      reviewCount: 87,
      featured: true,
      instantBooking: false,
      status: 'active',
      includes: ['Balloon flight', 'Champagne breakfast', 'Flight certificate', 'Game drive transfer'],
      excludes: ['Tips', 'Park entry fees'],
      tags: ['Sunrise', 'Balloon', 'Safari', 'Adventure'],
      totalBookings: 35,
      isDeleted: false,
      createdAt: new Date(),
    },
    {
      title: 'Naivasha Boat Safari & Crescent Island',
      slug: 'naivasha-boat',
      description: 'Boat across Lake Naivasha and walk among giraffes on Crescent Island.',
      destination: 'destination-mara-id',
      operator: 'operator-mara-id',
      category: 'adventure',
      images: ['https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800'],
      price: 55,
      currency: 'USD',
      duration: '1 day',
      groupSize: 10,
      rating: 4.6,
      reviewCount: 134,
      featured: true,
      instantBooking: true,
      status: 'active',
      includes: ['Boat ride', 'Island walk', 'Guide', 'Lunch'],
      excludes: ['Transport to Naivasha', 'Tips'],
      tags: ['Boat', 'Hippos', 'Walking Safari', 'Adventure'],
      totalBookings: 54,
      isDeleted: false,
      createdAt: new Date(),
    },
  ]

  // ─── GUIDES ────────────────────────────────────────────────────────────────
  const guides = [
    {
      user: 'guide-joseph-id',
      bio: 'KWS-certified safari guide with 12 years experience in Maasai Mara. Specialist in big cat behaviour and bird watching. Fluent in English, Swahili, and French.',
      languages: ['English', 'Swahili', 'French'],
      certifications: ['KWS Level 3', 'Wilderness First Aid', 'Bird Guide Certificate'],
      specializations: ['Big Five tracking', 'Bird watching', 'Photography safaris'],
      experience: 12,
      hourlyRate: 15,
      dailyRate: 80,
      rating: 5.0,
      reviewCount: 128,
      category: 'safari',
      verified: true,
      status: 'active',
      isDeleted: false,
      createdAt: new Date(),
    },
    {
      user: 'guide-amina-id',
      bio: 'Cultural and city guide with 8 years exploring Zanzibar\'s history, spice farms, and Stone Town. Passionate about Swahili heritage and coastal cuisine.',
      languages: ['English', 'Swahili', 'Arabic'],
      certifications: ['Tanzania Tourism Board Certified', 'Cultural Heritage Guide'],
      specializations: ['Stone Town history', 'Spice tours', 'Swahili culture', 'Street food'],
      experience: 8,
      hourlyRate: 12,
      dailyRate: 60,
      rating: 4.9,
      reviewCount: 95,
      category: 'cultural',
      verified: true,
      status: 'active',
      isDeleted: false,
      createdAt: new Date(),
    },
  ]

  // ─── ACCOMMODATIONS ────────────────────────────────────────────────────────
  const accommodations = [
    {
      name: 'Mara Serena Safari Lodge',
      slug: 'mara-serena-safari-lodge',
      type: 'lodge',
      destination: 'destination-mara-id',
      owner: 'operator-mara-id',
      description: 'Perched on a hill in the heart of the Maasai Mara, Mara Serena offers stunning panoramic views over the plains.',
      images: ['https://images.unsplash.com/photo-1540541338537-71001bab8c76?w=800'],
      pricePerNight: 320,
      currency: 'USD',
      rating: 4.9,
      reviewCount: 420,
      amenities: ['Swimming pool', 'Spa', 'WiFi', 'Restaurant', 'Bar', 'Game room', 'Laundry', 'Room service'],
      rooms: [{
        name: 'Savanna Room',
        description: 'Luxury room with savanna views',
        pricePerNight: 320,
        maxGuests: 2,
        amenities: ['AC', 'En-suite', 'Mini bar', 'Private deck'],
      }],
      coordinates: { lat: -1.502, lng: 35.145 },
      featured: true,
      status: 'active',
      isDeleted: false,
      createdAt: new Date(),
    },
    {
      name: 'Zanzibar Reef Beach Resort',
      slug: 'zanzibar-reef-beach-resort',
      type: 'resort',
      destination: 'destination-zanzibar-id',
      owner: 'operator-mara-id',
      description: 'Beachfront resort in Nungwi with direct access to Zanzibar\'s most stunning coral reef.',
      images: ['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800'],
      pricePerNight: 180,
      currency: 'USD',
      rating: 4.8,
      reviewCount: 310,
      amenities: ['Beachfront', 'Pool', 'Spa', 'Snorkeling', 'Restaurant', 'WiFi', 'Water sports'],
      coordinates: { lat: -5.723, lng: 39.302 },
      featured: true,
      status: 'active',
      isDeleted: false,
      createdAt: new Date(),
    },
  ]

  // ─── REVIEWS ───────────────────────────────────────────────────────────────
  const reviews = [
    {
      user: 'tourist-john-id',
      targetType: 'tour',
      targetId: 'tour-mara-safari', // Will be replaced with actual tour ID
      rating: 5,
      title: 'Absolutely life-changing experience!',
      body: 'Our guide spotted a leopard on the first morning and we witnessed a lion kill on day 3. Joseph was phenomenal — knowledgeable, passionate, and incredibly skilled. Tembea Africa made the whole trip effortless from booking to departure.',
      verified: true,
      approved: true,
      isDeleted: false,
      createdAt: new Date(),
    },
    {
      user: 'tourist-sarah-id',
      targetType: 'tour',
      targetId: 'tour-mara-safari', // Will be replaced with actual tour ID
      rating: 5,
      title: 'Best safari in Africa — period',
      body: 'Saw all Big Five within the first two days. The balloon safari on day 3 was the most magical experience of my life. The camp was incredible and the food was outstanding. Will definitely be back!',
      verified: true,
      approved: true,
      isDeleted: false,
      createdAt: new Date(),
    },
  ]

  return {
    clearCollections: true,
    collections: {
      users,
      destinations,
      tours,
      guides,
      accommodations,
      reviews,
    },
  }
}
