/**
 * Seed data configuration for the Tembea Africa database.
 * This file defines all static seed data and makes it easy to add more.
 * To add new seed data:
 * 1. Add it to the appropriate collection below
 * 2. It will automatically be included when seeding
 */

import * as bcrypt from 'bcryptjs'

export interface SeedConfig {
  clearCollections: boolean  // Clear existing data before seeding
  collections: {
    [key: string]: any[]
  }
}

export async function generateSeedData(): Promise<SeedConfig> {
  const hashedPassword = await bcrypt.hash('Hamp9map....#', 12)

  // ─── USERS ─────────────────────────────────────────────────────────────────
  const users = [
    {
      _id: 'admin-user-id',
      firstName: 'Admin',
      lastName: 'Tembea',
      email: 'tembeaafricake@gmail.com',
      password: hashedPassword,
      role: 'admin',
      isVerified: true,
      createdAt: new Date(),
    },
    {
      _id: 'guide-joseph-id',
      firstName: 'Joseph',
      lastName: 'Kamau',
      email: 'joseph@tembeaafrica.com',
      password: hashedPassword,
      role: 'guide',
      isVerified: true,
      createdAt: new Date(),
    },
    {
      _id: 'guide-amina-id',
      firstName: 'Amina',
      lastName: 'Mohamed',
      email: 'amina@tembeaafrica.com',
      password: hashedPassword,
      role: 'guide',
      isVerified: true,
      createdAt: new Date(),
    },
    {
      _id: 'tourist-john-id',
      firstName: 'John',
      lastName: 'Traveller',
      email: 'john@example.com',
      password: hashedPassword,
      role: 'tourist',
      isVerified: true,
      createdAt: new Date(),
    },
    {
      _id: 'tourist-sarah-id',
      firstName: 'Sarah',
      lastName: 'Williams',
      email: 'sarah@example.com',
      password: hashedPassword,
      role: 'tourist',
      isVerified: true,
      nationality: 'United Kingdom',
      createdAt: new Date(),
    },
    {
      _id: 'operator-mara-id',
      firstName: 'Mara',
      lastName: 'Safaris',
      email: 'operator@marasafaris.com',
      password: hashedPassword,
      role: 'operator',
      isVerified: true,
      createdAt: new Date(),
    },
  ]

  // ─── DESTINATIONS ──────────────────────────────────────────────────────────
  const destinations = [
    {
      _id: 'destination-mara-id',
      name: 'Maasai Mara',
      slug: 'maasai-mara',
      country: 'kenya',
      county: 'Narok',
      description: 'Home to the Great Wildebeest Migration and Africa\'s finest Big Five wildlife viewing.',
      heroImage: 'https://images.unsplash.com/photo-1547970810-dc1eac37d174?w=1200',
      images: ['https://images.unsplash.com/photo-1547970810-dc1eac37d174?w=800'],
      coordinates: { lat: -1.5001, lng: 35.1399 },
      rating: 4.9,
      reviewCount: 1240,
      tourCount: 86,
      hotelCount: 45,
      tags: ['Wildlife', 'Safari', 'Migration', 'Big Five'],
      bestTimeToVisit: 'July–October',
      featured: true,
      status: 'active',
      travelTips: 'Book sunrise game drives for best predator sightings.',
      visaInfo: 'Kenya eVisa available online at $51.',
      createdAt: new Date(),
    },
    {
      _id: 'destination-zanzibar-id',
      name: 'Zanzibar',
      slug: 'zanzibar',
      country: 'tanzania',
      description: 'Pristine white sandy beaches, turquoise Indian Ocean waters, and rich Swahili cultural heritage.',
      heroImage: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200',
      images: ['https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800'],
      coordinates: { lat: -6.1659, lng: 39.2026 },
      rating: 4.8,
      reviewCount: 890,
      tourCount: 54,
      hotelCount: 120,
      tags: ['Beach', 'Culture', 'Diving', 'Spice'],
      bestTimeToVisit: 'June–October',
      featured: true,
      status: 'active',
      createdAt: new Date(),
    },
    {
      _id: 'destination-kilimanjaro-id',
      name: 'Kilimanjaro',
      slug: 'kilimanjaro',
      country: 'tanzania',
      description: 'Africa\'s highest peak at 5,895m. The ultimate trekking challenge attracting climbers from across the globe.',
      heroImage: 'https://images.unsplash.com/photo-1621414050345-53db43f7e7ab?w=1200',
      images: ['https://images.unsplash.com/photo-1621414050345-53db43f7e7ab?w=800'],
      coordinates: { lat: -3.0674, lng: 37.3556 },
      rating: 4.9,
      reviewCount: 620,
      tourCount: 32,
      hotelCount: 28,
      tags: ['Trekking', 'Adventure', 'Mountain', 'Summit'],
      bestTimeToVisit: 'January–March, June–October',
      featured: true,
      status: 'active',
      createdAt: new Date(),
    },
    {
      _id: 'destination-serengeti-id',
      name: 'Serengeti',
      slug: 'serengeti',
      country: 'tanzania',
      description: 'Endless golden plains hosting the world\'s greatest wildlife spectacle — year-round Big Five and the Great Migration.',
      heroImage: 'https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=1200',
      images: ['https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=800'],
      coordinates: { lat: -2.3333, lng: 34.8333 },
      rating: 5.0,
      reviewCount: 1100,
      tourCount: 98,
      hotelCount: 62,
      tags: ['Wildlife', 'Safari', 'Photography', 'Migration'],
      bestTimeToVisit: 'June–September',
      featured: true,
      status: 'active',
      createdAt: new Date(),
    },
    {
      _id: 'destination-mombasa-id',
      name: 'Mombasa',
      slug: 'mombasa',
      country: 'kenya',
      description: 'Kenya\'s vibrant coastal city blending Old Town Swahili heritage with beautiful Indian Ocean beaches.',
      heroImage: 'https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=1200',
      images: ['https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=800'],
      coordinates: { lat: -4.0435, lng: 39.6682 },
      rating: 4.7,
      reviewCount: 980,
      tourCount: 71,
      hotelCount: 134,
      tags: ['Beach', 'History', 'Culture', 'City'],
      bestTimeToVisit: 'October–April',
      featured: true,
      status: 'active',
      createdAt: new Date(),
    },
    {
      _id: 'destination-diani-id',
      name: 'Diani Beach',
      slug: 'diani-beach',
      country: 'kenya',
      description: 'Kenya\'s most celebrated beach — 17km of powder-white sand, coral reefs, and world-class resorts.',
      heroImage: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1200',
      images: ['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800'],
      coordinates: { lat: -4.2947, lng: 39.5748 },
      rating: 4.8,
      reviewCount: 560,
      tourCount: 38,
      hotelCount: 67,
      tags: ['Beach', 'Snorkeling', 'Relaxation', 'Diving'],
      bestTimeToVisit: 'December–April',
      featured: true,
      status: 'active',
      createdAt: new Date(),
    },
  ]

  // ─── TOURS ─────────────────────────────────────────────────────────────────
  const tours = [
    {
      title: '5-Day Maasai Mara Safari — Big Five Guaranteed',
      slug: 'maasai-mara-big-five-5day',
      description: 'Immerse yourself in the heart of the Maasai Mara on this 5-day safari. Witness lions, leopards, elephants, buffalos, and rhinos up close.',
      destination: 'destination-mara-id',
      operator: 'operator-mara-id',
      category: 'safari',
      images: ['https://images.unsplash.com/photo-1547970810-dc1eac37d174?w=800'],
      price: 480,
      currency: 'USD',
      duration: '5 days',
      groupSize: 8,
      rating: 4.9,
      reviewCount: 312,
      featured: true,
      instantBooking: true,
      status: 'active',
      includes: ['4WD safari vehicle', 'Professional guide', 'Park fees', 'Accommodation', 'All meals', 'Airport pickup'],
      excludes: ['International flights', 'Travel insurance', 'Tips', 'Personal items'],
      tags: ['Safari', 'Big Five', 'Luxury', 'Kenya'],
      totalBookings: 156,
      isDeleted: false,
      createdAt: new Date(),
    },
    {
      title: 'Zanzibar Island Dhow Cruise & Spice Tour',
      slug: 'zanzibar-dhow-cruise-spice',
      description: 'Sail on a traditional wooden dhow along Zanzibar\'s turquoise coast, then explore fragrant spice plantations.',
      destination: 'destination-zanzibar-id',
      operator: 'operator-mara-id',
      category: 'beach',
      images: ['https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800'],
      price: 75,
      currency: 'USD',
      duration: '1 day',
      groupSize: 12,
      rating: 4.8,
      reviewCount: 197,
      featured: true,
      instantBooking: true,
      status: 'active',
      includes: ['Dhow boat', 'Snorkeling equipment', 'Lunch on boat', 'Spice farm entry', 'Guide'],
      excludes: ['Hotel pickup', 'Alcoholic drinks'],
      tags: ['Beach', 'Dhow', 'Spices', 'Snorkeling'],
      totalBookings: 89,
      isDeleted: false,
      createdAt: new Date(),
    },
    {
      title: 'Kilimanjaro Summit Trek — 7 Days Machame Route',
      slug: 'kilimanjaro-machame-7day',
      description: 'Conquer Africa\'s highest peak via the scenic Machame "Whiskey" route with our KWS-certified mountain guides.',
      destination: 'destination-kilimanjaro-id',
      operator: 'operator-mara-id',
      category: 'mountain',
      images: ['https://images.unsplash.com/photo-1621414050345-53db43f7e7ab?w=800'],
      price: 1850,
      currency: 'USD',
      duration: '7 days',
      groupSize: 6,
      rating: 4.9,
      reviewCount: 88,
      featured: true,
      instantBooking: false,
      status: 'active',
      includes: ['KWS-certified guide', 'Porters', 'All meals on mountain', 'Camping equipment', 'Park fees', 'Transfers'],
      excludes: ['International flights', 'Sleeping bag', 'Tips', 'Travel insurance'],
      tags: ['Trekking', 'Summit', 'Adventure', 'Mountain'],
      totalBookings: 42,
      isDeleted: false,
      createdAt: new Date(),
    },
    {
      title: 'Maasai Mara Balloon Safari at Sunrise',
      slug: 'mara-balloon',
      description: 'Float above the Mara at dawn with champagne breakfast. Witness wildlife migrations from a birds-eye view.',
      destination: 'destination-mara-id',
      operator: 'operator-mara-id',
      category: 'adventure',
      images: ['https://images.unsplash.com/photo-1547970810-dc1eac37d174?w=800'],
      price: 320,
      currency: 'USD',
      duration: '4 hours',
      groupSize: 8,
      rating: 5.0,
      reviewCount: 87,
      featured: true,
      instantBooking: false,
      status: 'active',
      includes: ['Balloon flight', 'Champagne breakfast', 'Flight certificate', 'Game drive transfer'],
      excludes: ['Tips', 'Park entry fees'],
      tags: ['Sunrise', 'Balloon', 'Safari', 'Adventure'],
      totalBookings: 35,
      isDeleted: false,
      createdAt: new Date(),
    },
    {
      title: 'Naivasha Boat Safari & Crescent Island',
      slug: 'naivasha-boat',
      description: 'Boat across Lake Naivasha and walk among giraffes on Crescent Island.',
      destination: 'destination-mara-id',
      operator: 'operator-mara-id',
      category: 'adventure',
      images: ['https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800'],
      price: 55,
      currency: 'USD',
      duration: '1 day',
      groupSize: 10,
      rating: 4.6,
      reviewCount: 134,
      featured: true,
      instantBooking: true,
      status: 'active',
      includes: ['Boat ride', 'Island walk', 'Guide', 'Lunch'],
      excludes: ['Transport to Naivasha', 'Tips'],
      tags: ['Boat', 'Hippos', 'Walking Safari', 'Adventure'],
      totalBookings: 54,
      isDeleted: false,
      createdAt: new Date(),
    },
  ]


  // ─── GUIDES ─────────────────────────────────────────────────────────────────
  const guides = [
    {
      _id: "6a5397a544de40974f0ff101",
      user: "6a5397a544de40974f0ee101",
      firstName: "Samson",
      lastName: "Ole Sankale",
      email: "samson.olesankale@tembeaafrica.com",
      avatar: null,
      bio: "Professional safari guide based in Maasai Mara with extensive experience tracking the Big Five, interpreting wildlife behaviour, and leading luxury game drives.",
      languages: ["English", "Swahili"],
      certifications: ["KWS Level 3", "Wilderness First Aid"],
      specializations: ["Big Five Tracking", "Game Drives", "Wildlife Conservation"],
      experience: 12,
      hourlyRate: 20,
      dailyRate: 120,
      rating: 4.9,
      reviewCount: 184,
      portfolio: [],
      availability: [],
      category: "safari",
      verified: true,
      status: "active",
      isDeleted: false,
      createdAt: new Date("2026-07-16T08:07:15.000Z"),
      updatedAt: new Date("2026-07-16T08:07:15.000Z"),
    },
    {
      _id: "6a5397a544de40974f0ff102",
      user: "6a5397a544de40974f0ee102",
      firstName: "Emmanuel",
      lastName: "Ole Parsitau",
      email: "emmanuel.oleparsitau@tembeaafrica.com",
      avatar: null,
      bio: "Experienced Serengeti safari guide specializing in the Great Migration and luxury wildlife expeditions across northern Tanzania.",
      languages: ["English", "Swahili"],
      certifications: ["TATO Guide License", "First Aid"],
      specializations: ["Great Migration", "Wildlife Photography", "Luxury Safaris"],
      experience: 14,
      hourlyRate: 24,
      dailyRate: 145,
      rating: 5.0,
      reviewCount: 215,
      portfolio: [],
      availability: [],
      category: "safari",
      verified: true,
      status: "active",
      isDeleted: false,
      createdAt: new Date("2026-07-16T08:07:15.000Z"),
      updatedAt: new Date("2026-07-16T08:07:15.000Z"),
    },
    {
      _id: "6a5397a544de40974f0ff103",
      user: "6a5397a544de40974f0ee103",
      firstName: "Daniel",
      lastName: "Ole Nkoisiai",
      email: "daniel.olenkoisiai@tembeaafrica.com",
      avatar: null,
      bio: "Certified safari guide offering unforgettable wildlife experiences in Tsavo East and Tsavo West National Parks.",
      languages: ["English", "Swahili"],
      certifications: ["KWS Level 2", "Emergency First Aid"],
      specializations: ["Elephant Tracking", "Bird Watching", "Family Safaris"],
      experience: 10,
      hourlyRate: 18,
      dailyRate: 110,
      rating: 4.8,
      reviewCount: 143,
      portfolio: [],
      availability: [],
      category: "safari",
      verified: true,
      status: "active",
      isDeleted: false,
      createdAt: new Date("2026-07-16T08:07:15.000Z"),
      updatedAt: new Date("2026-07-16T08:07:15.000Z"),
    },
    {
      _id: "6a5397a544de40974f0ff104",
      user: "6a5397a544de40974f0ee104",
      firstName: "Saitoti",
      lastName: "Ole Kimani",
      email: "saitoti.olekimani@tembeaafrica.com",
      avatar: null,
      bio: "Amboseli safari expert with deep knowledge of elephant conservation and Mount Kilimanjaro viewing locations.",
      languages: ["English", "Swahili"],
      certifications: ["KWS Guide Certificate"],
      specializations: ["Elephants", "Nature Walks", "Photography"],
      experience: 11,
      hourlyRate: 19,
      dailyRate: 115,
      rating: 4.9,
      reviewCount: 169,
      portfolio: [],
      availability: [],
      category: "safari",
      verified: true,
      status: "active",
      isDeleted: false,
      createdAt: new Date("2026-07-16T08:07:15.000Z"),
      updatedAt: new Date("2026-07-16T08:07:15.000Z"),
    },
    {
      _id: "6a5397a544de40974f0ff105",
      user: "6a5397a544de40974f0ee105",
      firstName: "Lekipai",
      lastName: "Ole Tipis",
      email: "lekipai.oletipis@tembeaafrica.com",
      avatar: null,
      bio: "Lake Nakuru wildlife guide specializing in rhinos, flamingos, birdlife, and conservation education.",
      languages: ["English", "Swahili"],
      certifications: ["Bird Guide Certificate"],
      specializations: ["Rhino Tracking", "Bird Watching", "Photography"],
      experience: 9,
      hourlyRate: 17,
      dailyRate: 100,
      rating: 4.8,
      reviewCount: 132,
      portfolio: [],
      availability: [],
      category: "safari",
      verified: true,
      status: "active",
      isDeleted: false,
      createdAt: new Date("2026-07-16T08:07:15.000Z"),
      updatedAt: new Date("2026-07-16T08:07:15.000Z"),
    },
  ]


  // ─── ACCOMMODATIONS ────────────────────────────────────────────────────────
  const accommodationTemplates = [
    { name: 'Mara Serena Safari Lodge', slug: 'mara-serena-safari-lodge', type: 'hotel', destination: 'destination-mara-id', description: 'Perched on a hill in the heart of the Maasai Mara, Mara Serena offers stunning panoramic views over the plains.', images: ['https://images.unsplash.com/photo-1540541338537-71001bab8c76?w=800'], pricePerNight: 320, rating: 4.9, reviewCount: 420, amenities: ['Pool', 'Spa', 'WiFi', 'Restaurant', 'Bar', 'Game room', 'Laundry', 'Room service'], rooms: [{ name: 'Savanna Room', description: 'Luxury room with savanna views', pricePerNight: 320, maxGuests: 2, amenities: ['AC', 'En-suite', 'Mini bar', 'Private deck'] }], coordinates: { lat: -1.502, lng: 35.145 }, featured: true },
    { name: 'Zanzibar Reef Beach Resort', slug: 'zanzibar-reef-beach-resort', type: 'hotel', destination: 'destination-zanzibar-id', description: 'Beachfront resort in Nungwi with direct access to Zanzibar\'s most stunning coral reef.', images: ['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800'], pricePerNight: 180, rating: 4.8, reviewCount: 310, amenities: ['Beachfront', 'Pool', 'Spa', 'Snorkeling', 'Restaurant', 'WiFi', 'Water sports'], coordinates: { lat: -5.723, lng: 39.302 }, featured: true },
    { name: 'Kilimanjaro Mountain View Hotel', slug: 'kilimanjaro-mountain-view-hotel', type: 'hotel', destination: 'destination-kilimanjaro-id', description: 'A polished hotel with mountain views and easy access to Kilimanjaro National Park.', images: ['https://images.unsplash.com/photo-1621414050345-53db43f7e7ab?w=800'], pricePerNight: 190, rating: 4.8, reviewCount: 290, amenities: ['Fitness centre', 'WiFi', 'Restaurant', 'Spa'], rooms: [{ name: 'Summit Suite', description: 'Room with panoramic mountain views', pricePerNight: 190, maxGuests: 2, amenities: ['AC', 'En-suite', 'Balcony'] }], coordinates: { lat: -3.0674, lng: 37.3556 }, featured: true },
    { name: 'Serengeti Heritage Hotel', slug: 'serengeti-heritage-hotel', type: 'hotel', destination: 'destination-serengeti-id', description: 'Boutique hotel located near Serengeti plains with elegant rooms and safari packages.', images: ['https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=800'], pricePerNight: 260, rating: 4.9, reviewCount: 245, amenities: ['Restaurant', 'Safari lounge', 'WiFi', 'Laundry'], rooms: [{ name: 'Heritage Room', description: 'Comfortable room with safari decor', pricePerNight: 260, maxGuests: 2, amenities: ['En-suite', 'Private terrace'] }], coordinates: { lat: -2.3333, lng: 34.8333 }, featured: true },
    { name: 'Mombasa Coral Resort', slug: 'mombasa-coral-resort', type: 'hotel', destination: 'destination-mombasa-id', description: 'Coastal hotel with a coral reef-view terrace and direct access to the beach.', images: ['https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=800'], pricePerNight: 210, rating: 4.7, reviewCount: 198, amenities: ['Beach access', 'Pool', 'Spa', 'Kids club'], rooms: [{ name: 'Ocean Room', description: 'Sea-view room with balcony', pricePerNight: 210, maxGuests: 3, amenities: ['AC', 'Mini fridge', 'WiFi'] }], coordinates: { lat: -4.0435, lng: 39.6682 }, featured: true },
    { name: 'Diani Beach Sun Resort', slug: 'diani-beach-sun-resort', type: 'hotel', destination: 'destination-diani-beach-id', description: 'Luxury beachfront hotel in Diani with sundowner decks and coral gardens.', images: ['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800'], pricePerNight: 240, rating: 4.8, reviewCount: 184, amenities: ['Beachfront', 'Pool', 'Spa', 'Water sports'], rooms: [{ name: 'Beach Suite', description: 'Spacious suite steps from the beach', pricePerNight: 240, maxGuests: 3, amenities: ['Private terrace', 'AC', 'WiFi'] }], coordinates: { lat: -4.2947, lng: 39.5748 }, featured: true },
    { name: 'Ngorongoro Crater Lodge', slug: 'ngorongoro-crater-lodge', type: 'hotel', destination: 'destination-ngorongoro-id', description: 'Luxury lodge on the rim of the Ngorongoro Crater featuring dramatic views and elegant tents.', images: ['https://images.unsplash.com/photo-1540202403-b7abd6747a18?w=800'], pricePerNight: 470, rating: 5.0, reviewCount: 142, amenities: ['Spa', 'Restaurant', 'Safari terrace', 'Free breakfast'], rooms: [{ name: 'Crater Suite', description: 'Luxury suite with crater views', pricePerNight: 470, maxGuests: 2, amenities: ['En-suite', 'Balcony', 'Room service'] }], coordinates: { lat: -3.2026, lng: 35.4866 }, featured: true },
    { name: 'Amboseli Sapphire Lodge', slug: 'amboseli-sapphire-lodge', type: 'hotel', destination: 'destination-amboseli-id', description: 'Elegant lodge offering dramatic views of Mount Kilimanjaro and intimate bush walks.', images: ['https://images.unsplash.com/photo-1551649001-7a2482d98d05?w=800'], pricePerNight: 230, rating: 4.8, reviewCount: 212, amenities: ['Pool', 'Restaurant', 'Guide desk', 'WiFi'], rooms: [{ name: 'Kili View Room', description: 'Room with Mt Kilimanjaro views', pricePerNight: 230, maxGuests: 2, amenities: ['AC', 'Private balcony', 'En-suite'] }], coordinates: { lat: -2.6527, lng: 37.2606 }, featured: true },
    { name: 'Zanzibar White Sand Hotel', slug: 'zanzibar-white-sand-hotel', type: 'hotel', destination: 'destination-zanzibar-id', description: 'Chic beach hotel on Zanzibar’s eastern shore with a spa, infinity pool, and deep ocean views.', images: ['https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800'], pricePerNight: 205, rating: 4.8, reviewCount: 278, amenities: ['Infinity pool', 'Spa', 'Beach bar', 'Restaurant'], rooms: [{ name: 'Ocean Deluxe', description: 'Luxury room with ocean panorama', pricePerNight: 205, maxGuests: 2, amenities: ['Balcony', 'AC', 'WiFi'] }], coordinates: { lat: -6.1659, lng: 39.2026 }, featured: true },
    { name: 'Mombasa Sea Cliff Hotel', slug: 'mombasa-sea-cliff-hotel', type: 'hotel', destination: 'destination-mombasa-id', description: 'Historic hotel perched on a scenic cliff, combining Swahili heritage with ocean views.', images: ['https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=800'], pricePerNight: 175, rating: 4.6, reviewCount: 198, amenities: ['Ocean terrace', 'Restaurant', 'WiFi', 'Fitness centre'], rooms: [{ name: 'Cliff View Room', description: 'Coastal room with balcony views', pricePerNight: 175, maxGuests: 2, amenities: ['AC', 'WiFi', 'Mini bar'] }], coordinates: { lat: -4.0435, lng: 39.6682 }, featured: false },
    { name: 'Kilimanjaro Wellness Hotel', slug: 'kilimanjaro-wellness-hotel', type: 'hotel', destination: 'destination-kilimanjaro-id', description: 'Boutique wellness hotel near Kilimanjaro basecamp with yoga, spa, and mountain scenery.', images: ['https://images.unsplash.com/photo-1621414050345-53db43f7e7ab?w=800'], pricePerNight: 170, rating: 4.7, reviewCount: 112, amenities: ['Spa', 'Yoga classes', 'Restaurant', 'WiFi'], rooms: [{ name: 'Wellness Suite', description: 'Calming suite with garden views', pricePerNight: 170, maxGuests: 2, amenities: ['En-suite', 'Balcony', 'AC'] }], coordinates: { lat: -3.0674, lng: 37.3556 }, featured: false },
    { name: 'Diani Palm Beach Hotel', slug: 'diani-palm-beach-hotel', type: 'hotel', destination: 'destination-diani-beach-id', description: 'Family-friendly beach hotel lined with swaying palms and a lagoon-style pool.', images: ['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800'], pricePerNight: 160, rating: 4.7, reviewCount: 145, amenities: ['Pool', 'Kids club', 'Beach bar', 'WiFi'], rooms: [{ name: 'Family Room', description: 'Spacious family room near the pool', pricePerNight: 160, maxGuests: 4, amenities: ['AC', 'Private terrace'] }], coordinates: { lat: -4.2947, lng: 39.5748 }, featured: false },
    { name: 'Mombasa Old Town Hotel', slug: 'mombasa-old-town-hotel', type: 'hotel', destination: 'destination-mombasa-id', description: 'A classic Swahili hotel in Old Town with rooftop dining and dhow harbour views.', images: ['https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=800'], pricePerNight: 145, rating: 4.5, reviewCount: 122, amenities: ['Rooftop restaurant', 'WiFi', 'Breakfast included'], rooms: [{ name: 'Heritage Room', description: 'Cozy room with traditional decor', pricePerNight: 145, maxGuests: 2, amenities: ['AC', 'En-suite'] }], coordinates: { lat: -4.0435, lng: 39.6682 }, featured: false },
    { name: 'Amboseli Elephant Hills Hotel', slug: 'amboseli-elephant-hills-hotel', type: 'hotel', destination: 'destination-amboseli-id', description: 'Contemporary hotel with expansive views of Amboseli plains and Kilimanjaro beyond.', images: ['https://images.unsplash.com/photo-1551649001-7a2482d98d05?w=800'], pricePerNight: 210, rating: 4.8, reviewCount: 176, amenities: ['Restaurant', 'Bar', 'Free parking', 'WiFi'], rooms: [{ name: 'Panorama Room', description: 'Room with sweeping landscape views', pricePerNight: 210, maxGuests: 2, amenities: ['AC', 'En-suite', 'Balcony'] }], coordinates: { lat: -2.6527, lng: 37.2606 }, featured: false },
    { name: 'Serengeti Nyani Tented Lodge', slug: 'serengeti-nyani-tented-lodge', type: 'hotel', destination: 'destination-serengeti-id', description: 'Eco-friendly tented lodge with direct access to photographer-friendly wildlife areas.', images: ['https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=800'], pricePerNight: 295, rating: 4.9, reviewCount: 158, amenities: ['Safari walks', 'Outdoor dining', 'WiFi'], rooms: [{ name: 'Tented Suite', description: 'Luxury tent with private deck', pricePerNight: 295, maxGuests: 2, amenities: ['Outdoor seating', 'En-suite'] }], coordinates: { lat: -2.3333, lng: 34.8333 }, featured: false },
    { name: 'Ngorongoro Rhino Safari Hotel', slug: 'ngorongoro-rhino-safari-hotel', type: 'hotel', destination: 'destination-ngorongoro-id', description: 'Rustic comfort near crater safari routes with excellent wildlife watching options.', images: ['https://images.unsplash.com/photo-1540202403-b7abd6747a18?w=800'], pricePerNight: 210, rating: 4.7, reviewCount: 118, amenities: ['Restaurant', 'Guided safaris', 'WiFi'], rooms: [{ name: 'Safari Room', description: 'Room with bush views', pricePerNight: 210, maxGuests: 2, amenities: ['AC', 'Private veranda'] }], coordinates: { lat: -3.2026, lng: 35.4866 }, featured: false },
    { name: 'Mara Plains Heritage Hotel', slug: 'mara-plains-heritage-hotel', type: 'hotel', destination: 'destination-mara-id', description: 'Elegant hotel with a lodge-style ambience and easy access to Maasai Mara game drives.', images: ['https://images.unsplash.com/photo-1547970810-dc1eac37d174?w=800'], pricePerNight: 250, rating: 4.8, reviewCount: 132, amenities: ['Restaurant', 'Pool', 'Safari concierge', 'WiFi'], rooms: [{ name: 'Heritage Suite', description: 'Spacious suite with bush views', pricePerNight: 250, maxGuests: 2, amenities: ['AC', 'En-suite', 'Balcony'] }], coordinates: { lat: -1.503, lng: 35.146 }, featured: false },
    { name: 'Zanzibar Ocean Reef Hotel', slug: 'zanzibar-ocean-reef-hotel', type: 'hotel', destination: 'destination-zanzibar-id', description: 'Stylish coastal hotel overlooking Zanzibar’s reef-lined shores and turquoise waters.', images: ['https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800'], pricePerNight: 220, rating: 4.8, reviewCount: 164, amenities: ['Beachfront', 'Pool', 'Spa', 'Beach bar', 'WiFi'], rooms: [{ name: 'Ocean View Room', description: 'Room with panoramic sea views', pricePerNight: 220, maxGuests: 2, amenities: ['Balcony', 'AC', 'WiFi'] }], coordinates: { lat: -6.1655, lng: 39.2030 }, featured: false },
    { name: 'Amboseli Kilimanjaro Hotel', slug: 'amboseli-kilimanjaro-hotel', type: 'hotel', destination: 'destination-amboseli-id', description: 'Modern hotel with direct views of Mount Kilimanjaro and guided wildlife excursions.', images: ['https://images.unsplash.com/photo-1551649001-7a2482d98d05?w=800'], pricePerNight: 180, rating: 4.7, reviewCount: 136, amenities: ['Pool', 'Restaurant', 'WiFi', 'Tour desk'], rooms: [{ name: 'Kili View Room', description: 'Room with unobstructed mountain views', pricePerNight: 180, maxGuests: 2, amenities: ['AC', 'En-suite', 'Balcony'] }], coordinates: { lat: -2.6550, lng: 37.2610 }, featured: false },
    { name: 'Mombasa Royal Marina Hotel', slug: 'mombasa-royal-marina-hotel', type: 'hotel', destination: 'destination-mombasa-id', description: 'Upscale hotel on the Mombasa marina with yacht club vibes and ocean dining.', images: ['https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=800'], pricePerNight: 205, rating: 4.7, reviewCount: 148, amenities: ['Marina access', 'Pool', 'Restaurant', 'WiFi'], rooms: [{ name: 'Marina Suite', description: 'Luxury suite with harbour views', pricePerNight: 205, maxGuests: 2, amenities: ['AC', 'En-suite', 'WiFi'] }], coordinates: { lat: -4.0438, lng: 39.6685 }, featured: false },
    { name: 'Mara River BnB', slug: 'mara-river-bnb', type: 'bnb', destination: 'destination-mara-id', description: 'Charming BnB beside the Mara River, ideal for guests seeking quiet safari mornings.', images: ['https://images.unsplash.com/photo-1547970810-dc1eac37d174?w=800'], pricePerNight: 95, rating: 4.7, reviewCount: 86, amenities: ['Breakfast included', 'Garden', 'WiFi'], coordinates: { lat: -1.510, lng: 35.147 }, featured: false },
    { name: 'Mara View Guesthouse', slug: 'mara-view-guesthouse', type: 'bnb', destination: 'destination-mara-id', description: 'Family-run guesthouse offering river views and easy access to game drives.', images: ['https://images.unsplash.com/photo-1547970810-dc1eac37d174?w=800'], pricePerNight: 85, rating: 4.6, reviewCount: 74, amenities: ['Breakfast', 'Garden terrace', 'WiFi'], coordinates: { lat: -1.508, lng: 35.150 }, featured: false },
    { name: 'Maasai Village BnB', slug: 'maasai-village-bnb', type: 'bnb', destination: 'destination-mara-id', description: 'Cozy BnB with traditional Maasai-inspired decor and cultural experiences nearby.', images: ['https://images.unsplash.com/photo-1547970810-dc1eac37d174?w=800'], pricePerNight: 75, rating: 4.5, reviewCount: 59, amenities: ['Breakfast', 'Cultural activities', 'WiFi'], coordinates: { lat: -1.495, lng: 35.140 }, featured: false },
    { name: 'Serengeti Sunrise BnB', slug: 'serengeti-sunrise-bnb', type: 'bnb', destination: 'destination-serengeti-id', description: 'A small reset BnB offering sunrise views over the Serengeti plains.', images: ['https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=800'], pricePerNight: 88, rating: 4.6, reviewCount: 51, amenities: ['Breakfast', 'Terrace', 'WiFi'], coordinates: { lat: -2.335, lng: 34.840 }, featured: false },
    { name: 'Serengeti Family BnB', slug: 'serengeti-family-bnb', type: 'bnb', destination: 'destination-serengeti-id', description: 'Family-friendly BnB with easy access to park gates and family safari packages.', images: ['https://images.unsplash.com/photo-1534177616072-ef7dc120449d?w=800'], pricePerNight: 98, rating: 4.6, reviewCount: 45, amenities: ['Family rooms', 'Breakfast', 'Garden'], coordinates: { lat: -2.340, lng: 34.838 }, featured: false },
    { name: 'Ngorongoro Eco BnB', slug: 'ngorongoro-eco-bnb', type: 'bnb', destination: 'destination-ngorongoro-id', description: 'Eco-conscious BnB with solar power and local cuisine, just minutes from the crater rim.', images: ['https://images.unsplash.com/photo-1540202403-b7abd6747a18?w=800'], pricePerNight: 110, rating: 4.8, reviewCount: 63, amenities: ['Eco-friendly', 'Breakfast', 'Garden'], coordinates: { lat: -3.200, lng: 35.485 }, featured: false },
    { name: 'Amboseli Garden BnB', slug: 'amboseli-garden-bnb', type: 'bnb', destination: 'destination-amboseli-id', description: 'Friendly garden BnB with views of Amboseli’s elephant plains and evening braais.', images: ['https://images.unsplash.com/photo-1551649001-7a2482d98d05?w=800'], pricePerNight: 105, rating: 4.7, reviewCount: 68, amenities: ['Garden', 'Breakfast', 'WiFi'], coordinates: { lat: -2.655, lng: 37.262 }, featured: false },
    { name: 'Zanzibar Stone Town BnB', slug: 'zanzibar-stone-town-bnb', type: 'bnb', destination: 'destination-zanzibar-id', description: 'Cultural BnB in Stone Town with classic Swahili architecture and rooftop views.', images: ['https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800'], pricePerNight: 120, rating: 4.8, reviewCount: 84, amenities: ['Roof terrace', 'Breakfast', 'WiFi'], coordinates: { lat: -6.165, lng: 39.202 }, featured: false },
    { name: 'Zanzibar Beachfront BnB', slug: 'zanzibar-beachfront-bnb', type: 'bnb', destination: 'destination-zanzibar-id', description: 'Relaxed beachfront BnB on the east coast of Zanzibar with personalized service.', images: ['https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800'], pricePerNight: 135, rating: 4.7, reviewCount: 96, amenities: ['Beach access', 'Breakfast', 'WiFi'], coordinates: { lat: -6.160, lng: 39.205 }, featured: false },
    { name: 'Diani Coastal BnB', slug: 'diani-coastal-bnb', type: 'bnb', destination: 'destination-diani-beach-id', description: 'Coastal BnB with a relaxed beachhouse atmosphere and easy access to Diani Beach.', images: ['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800'], pricePerNight: 115, rating: 4.6, reviewCount: 72, amenities: ['Beach access', 'Breakfast', 'Garden'], coordinates: { lat: -4.295, lng: 39.575 }, featured: false },
    { name: 'Mombasa Swahili House BnB', slug: 'mombasa-swahili-house-bnb', type: 'bnb', destination: 'destination-mombasa-id', description: 'Heritage Swahili house BnB with carved wood details and traditional breakfast.', images: ['https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=800'], pricePerNight: 99, rating: 4.5, reviewCount: 57, amenities: ['Breakfast', 'Heritage decor', 'WiFi'], coordinates: { lat: -4.044, lng: 39.666 }, featured: false },
    { name: 'Mombasa Old Harbour BnB', slug: 'mombasa-old-harbour-bnb', type: 'bnb', destination: 'destination-mombasa-id', description: 'Quaint harbour-facing BnB offering sunrise views and local seafood dining nearby.', images: ['https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=800'], pricePerNight: 105, rating: 4.6, reviewCount: 61, amenities: ['Breakfast', 'Harbour views', 'WiFi'], coordinates: { lat: -4.042, lng: 39.669 }, featured: false },
    { name: 'Kilimanjaro Basecamp BnB', slug: 'kilimanjaro-basecamp-bnb', type: 'bnb', destination: 'destination-kilimanjaro-id', description: 'Comfortable BnB located near the start of Kilimanjaro trekking routes.', images: ['https://images.unsplash.com/photo-1621414050345-53db43f7e7ab?w=800'], pricePerNight: 130, rating: 4.7, reviewCount: 79, amenities: ['Breakfast', 'Lounge', 'WiFi'], coordinates: { lat: -3.065, lng: 37.358 }, featured: false },
    { name: 'Kilimanjaro Coffee Farm BnB', slug: 'kilimanjaro-coffee-farm-bnb', type: 'bnb', destination: 'destination-kilimanjaro-id', description: 'Rustic coffee farm BnB offering fresh coffee tours and mountain views.', images: ['https://images.unsplash.com/photo-1621414050345-53db43f7e7ab?w=800'], pricePerNight: 125, rating: 4.8, reviewCount: 83, amenities: ['Breakfast', 'Coffee tour', 'Garden'], coordinates: { lat: -3.068, lng: 37.357 }, featured: false },
    { name: 'Diani Coconut Grove BnB', slug: 'diani-coconut-grove-bnb', type: 'bnb', destination: 'destination-diani-beach-id', description: 'Friendly coconut grove BnB steps away from Diani Beach and local kite surfing spots.', images: ['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800'], pricePerNight: 118, rating: 4.6, reviewCount: 64, amenities: ['Garden', 'Breakfast', 'WiFi'], coordinates: { lat: -4.296, lng: 39.574 }, featured: false },
    { name: 'Zanzibar Sunset Cottage', slug: 'zanzibar-sunset-cottage', type: 'bnb', destination: 'destination-zanzibar-id', description: 'Quiet cottage on Zanzibar’s west coast with sunset terrace and ocean breeze.', images: ['https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800'], pricePerNight: 140, rating: 4.9, reviewCount: 102, amenities: ['Sunset terrace', 'Breakfast', 'WiFi'], coordinates: { lat: -6.168, lng: 39.200 }, featured: false },
    { name: 'Mara Bush Garden BnB', slug: 'mara-bush-garden-bnb', type: 'bnb', destination: 'destination-mara-id', description: 'Boutique BnB with a lush garden setting and easy access to Mara game drives.', images: ['https://images.unsplash.com/photo-1547970810-dc1eac37d174?w=800'], pricePerNight: 92, rating: 4.6, reviewCount: 67, amenities: ['Garden', 'Breakfast', 'WiFi'], coordinates: { lat: -1.499, lng: 35.142 }, featured: false },
    { name: 'Amboseli Sunset BnB', slug: 'amboseli-sunset-bnb', type: 'bnb', destination: 'destination-amboseli-id', description: 'Sunset BnB near Amboseli with Kilimanjaro views and relaxed evening bonfires.', images: ['https://images.unsplash.com/photo-1551649001-7a2482d98d05?w=800'], pricePerNight: 108, rating: 4.7, reviewCount: 53, amenities: ['Breakfast', 'Bonfire', 'WiFi'], coordinates: { lat: -2.656, lng: 37.261 }, featured: false },
    { name: 'Ngorongoro Crater View BnB', slug: 'ngorongoro-crater-view-bnb', type: 'bnb', destination: 'destination-ngorongoro-id', description: 'Small BnB with crater rim views and a calm atmosphere after long safari days.', images: ['https://images.unsplash.com/photo-1540202403-b7abd6747a18?w=800'], pricePerNight: 115, rating: 4.8, reviewCount: 71, amenities: ['Breakfast', 'Garden', 'WiFi'], coordinates: { lat: -3.203, lng: 35.488 }, featured: false },
    { name: 'Zanzibar Spice Villa BnB', slug: 'zanzibar-spice-villa-bnb', type: 'bnb', destination: 'destination-zanzibar-id', description: 'Charming villa surrounded by spice trees and just a short walk from the beach.', images: ['https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800'], pricePerNight: 148, rating: 4.9, reviewCount: 91, amenities: ['Spice garden', 'Breakfast', 'WiFi'], coordinates: { lat: -6.166, lng: 39.203 }, featured: false },
  ]

  const accommodations = accommodationTemplates.map((template) => ({
    ...template,
    owner: 'operator-mara-id',
    currency: 'USD',
    status: 'active',
    isDeleted: false,
    createdAt: new Date(),
  }))

  // ─── TRANSPORT ─────────────────────────────────────────────────────────────
  const transports = [
    {
      _id: 'transport-nairobi-mara-shuttle',
      name: 'Nairobi → Maasai Mara Shuttle',
      type: 'bus',
      route: 'Nairobi - Maasai Mara',
      price: 45,
      currency: 'USD',
      duration: '5 hours',
      rating: 4.6,
      reviewCount: 89,
      description: 'Daily comfortable shuttle service from Nairobi to Maasai Mara with door-to-door pickup.',
      image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800',
      status: 'active',
      createdAt: new Date(),
    },
    {
      _id: 'transport-wilson-mara-flight',
      name: 'Wilson Airport → Maasai Mara Charter Flight',
      type: 'flight',
      route: 'Wilson Airport - Maasai Mara',
      price: 280,
      currency: 'USD',
      duration: '45 minutes',
      rating: 4.9,
      reviewCount: 67,
      description: 'Scenic charter flight from Nairobi Wilson to Maasai Mara airstrips, saving many hours on the road.',
      image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800',
      status: 'active',
      createdAt: new Date(),
    },
    {
      _id: 'transport-dar-zanzibar-ferry',
      name: 'Dar es Salaam → Zanzibar Ferry',
      type: 'ferry',
      route: 'Dar es Salaam - Zanzibar',
      price: 35,
      currency: 'USD',
      duration: '2 hours',
      rating: 4.5,
      reviewCount: 312,
      description: 'Fast ferry crossing from Dar es Salaam to Stone Town with comfortable seating and ocean views.',
      image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
      status: 'active',
      createdAt: new Date(),
    },
    {
      _id: 'transport-arusha-serengeti-transfer',
      name: 'Arusha → Serengeti Transfer',
      type: 'bus',
      route: 'Arusha - Serengeti',
      price: 55,
      currency: 'USD',
      duration: '6 hours',
      rating: 4.7,
      reviewCount: 94,
      description: 'Shared transfer service from Arusha to Serengeti with pick-up at major hotels and camps.',
      image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800',
      status: 'active',
      createdAt: new Date(),
    },
    {
      _id: 'transport-mombasa-airport-transfer',
      name: 'Mombasa Airport Private Transfer',
      type: 'car',
      route: 'Moi Airport - Mombasa/Diani',
      price: 40,
      currency: 'USD',
      duration: '1-2 hours',
      rating: 4.6,
      reviewCount: 203,
      description: 'Private airport pickup service from Moi International Airport to Mombasa or Diani Beach hotels.',
      image: 'https://images.unsplash.com/photo-1449965405229-13993e5750de?w=800',
      status: 'active',
      createdAt: new Date(),
    },
    {
      _id: 'transport-kilimanjaro-basecamp-shuttle',
      name: 'Kilimanjaro Airport → Basecamp Shuttle',
      type: 'car',
      route: 'Kilimanjaro Airport - Kilimanjaro Basecamp',
      price: 75,
      currency: 'USD',
      duration: '1 hour',
      rating: 4.8,
      reviewCount: 56,
      description: 'Private transfer from Kilimanjaro Airport to basecamp lodges near Mount Kilimanjaro.',
      image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800',
      status: 'active',
      createdAt: new Date(),
    },
  ]

  // ─── REVIEWS ───────────────────────────────────────────────────────────────
  const reviews = [
    {
      user: 'tourist-john-id',
      targetType: 'tour',
      targetId: 'tour-mara-safari', // Will be replaced with actual tour ID
      rating: 5,
      title: 'Absolutely life-changing experience!',
      body: 'Our guide spotted a leopard on the first morning and we witnessed a lion kill on day 3. Joseph was phenomenal — knowledgeable, passionate, and incredibly skilled. Tembea Africa made the whole trip effortless from booking to departure.',
      verified: true,
      approved: true,
      isDeleted: false,
      createdAt: new Date(),
    },
    {
      user: 'tourist-sarah-id',
      targetType: 'tour',
      targetId: 'tour-mara-safari', // Will be replaced with actual tour ID
      rating: 5,
      title: 'Best safari in Africa — period',
      body: 'Saw all Big Five within the first two days. The balloon safari on day 3 was the most magical experience of my life. The camp was incredible and the food was outstanding. Will definitely be back!',
      verified: true,
      approved: true,
      isDeleted: false,
      createdAt: new Date(),
    },
  ]

  return {
    clearCollections: true,
    collections: {
      users,
      destinations,
      tours,
      guides,
      accommodations,
      transport: transports,
      reviews,
    },
  }
}
